koordinates/geoserver

- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/Feature.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureCount.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/map/AbstractLayerOrTable.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/QueryControllerTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/model/feature/FeatureSchemaTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/translate/feature/FeatureDAOTest.java
This PR also has some other minor improvements, such as:
- Removing the feature ID from the feature object (It is already inside `feature.attributes`)
- Keeping the objectid alias consistent with the field name
- Set the name of the feature layer to its title
With our current PoC we're able to _attempt_ to load data into ArcPro, however the actual geometry/attribute data isn't loaded. ArcPro correctly zooms to the right area, and the attribute table has the right column names, but the data itself doesn't load.
Debugging with Charles Proxy; ArcPRO was making a query request with `returnCountOnly=true`. However, this parameter wasn't enabled for GSR. It was expecting a response with `"count": 123` but was returning a normal `/query` response. 
It was confirmed that it was making this …
> GSR: Add FeatureCount Model to enable `returnCountOnly` feature query

- src/community/gsr/src/main/java/org/geoserver/gsr/api/catalog/CatalogServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerListController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/ExportMapController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/GenerateKMLController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/LayerListController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/MapServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureServiceRoot.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/map/LayersAndTables.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/service/GeometryService.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/map/LayerDAO.java
- src/community/gsr/src/test/java/org/geoserver/gsr/QGISIntegrationTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/api/map/ExportMapControllerTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/api/map/GenerateKMLControllerTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/CatalogServiceControllerTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/ServiceTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/feature/FeatureControllerTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/feature/FeatureLayerControllerTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/feature/FeatureLayerListControllerTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/feature/FeatureServiceControllerTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/LayerListControllerTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/MapServiceControllerTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/QueryControllerTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/QueryControllerTimeTest.java
Sqashed commits: 5a1fb6b775e18d5c28add2ffc743cb8d0cfa855c, cb29c960a1f617f0841eee7ce14343839662c9d5, 1ac5675cce23ea51fa42628e48e585a8240ebd72
This change reshuffles the API structure such that each layer exists as a standalone folder and  has its own FeatureService or MapService.
This is to avoid issues with ArcPro attempting to enumerate all sibling layers within a particular folder/service when added to the map, and to make the API endpoints more addressable (avoid the numeric-indexing issue).
This PR also disables access to Geometry Service. 
This does geometry processing that we don't want at the moment.
Shuffled the whole API endpoints to match the following scheme:
```
.../services  # will list the workspaces
.../services/example  # will list the layers in the workspace …
```
> GSR: Re-arrange layers within the GSR service index

- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/QueryControllerTest.java
Big layers with LOTs of feature objects like layer-7251 and layer-7252 (linz.staging.kx.gd) fails to load its features on ArcPRO, as it tries to POST to the `/query` endpoint in hopes to fetch the geometries. 
It seems like ArcPRO does a `POST` query instead of a `GET` when there are lots of feature objects. It's basically trying to do the same as a GET query to get the geometries, so enable POST to return the same response.
Added a `POSTMapServerQuery` endpoint to function exactly like how it would do with `GET`
There shouldn't be any.
It's certainly not a snappy performance since there are lots of features (500000+) when this request is called.
> GSR: Enable POST to feature layer query endpoint

- src/community/gsr/src/main/java/org/geoserver/gsr/api/GSRRestConfig.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureLayer.java
- src/community/gsr/src/main/resources/applicationContext.xml
We don't want testers to be able to access the demo data in GSR. 
The GSR plugin also supports data editing.
Although KX authentication layer should block this (we never propagate editing permissions to GS), safe to disable this feature in general. 
Commented the mapping to the demo resource, and the handler.
Let editing be conditional on a property key `DISABLE_GSR_EDIT_KEY`
> GSR: Disable access to demo data and editing

- src/community/gsr/src/main/java/org/geoserver/gsr/api/catalog/CatalogServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerListController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/LayerListController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/MapServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/map/LayerDAO.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/feature/FeatureLayerListControllerTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/QueryControllerTimeTest.java
Currently, if you hit a endpoint with:
- an invalid layer/workspace name: `rest/services/weirdname/layer-unknown/`
- or an endpoint that doesn't exist: `rest/services/example.com/layer-123/UnknownServer/` 
It will return a 500 response. Either because it was throwing a `NoSuchElementException` (intentional) or a `NullPointerException` (when a layer could not be found' not handled).
We want to change it to a 404 response with a meaningful error message. 
These changes will handle exceptions thrown in GSR more gracefully. There were lots of areas that could throw a `NullPointerException`, especially if an invalid layer was trying to be retrieved.
> GSR: Return 404 for invalid/non-existent endpoints

- src/community/gsr/pom.xml
- src/community/gsr/src/main/java/org/geoserver/gsr/GSRMonitorCallback.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/GenerateKMLController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/relationship/RelationshipController.java
- src/community/gsr/src/main/resources/applicationContext.xml
- src/extension/monitor/core/src/main/java/org/geoserver/monitor/ows/MonitorCallback.java
- src/extension/monitor/core/src/main/resources/org/geoserver/monitor/filter.properties
WIP — needs more work on:
* dealing with endpoints like `/query` that take querystring parameters: right now these get merged with the URL path variables into resources.
* more work on service/operation/suboperation naming: there's some unnamed endpoints
* for FeatureServer/MapServer, it'd be more use to return the actual layer qnames from the catalog rather than the server name & layer index. For `/myworkspace/rest/services/myworkspace/mylayer/FeatureServer/0` it's nbd since it's always `0` but that won't always be the case.
Right now it populates the service as "GSR" consistently; populates Operation; adds the path + view query parameters to resources. And does it without breaking either Monitor or GSR.
> GSR: Add monitoring support

- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureServiceController.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/feature/FeatureServiceControllerTest.java
In AGOL experience builder, tables don't seem to want to load our attribute data. This might be related to POST to `/FeatureServer/` throwing 500 errors. It looks like Esri expects a POST to this API to return the same content as a GET
Add support for POST requests to this endpoint, returning the same content as a GET request.
Added `RequestMethod.POST` to the available methods in the endpoint mappings.
> GSR: Enable POST to feature server endpoint

- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/QueryControllerTest.java
If you include `returnIdsOnly=true` _and_ `returnCountOnly=true` then AGOL expects the `count: ...` only, whereas we return the ids only.
E.g. the output of a request to
```.../FeatureServer/0/query?f=json&returnIdsOnly=true&returnCountOnly=true&returnGeometry=false&spatialRel=esriSpatialRelIntersects&where=1%3D1```
should match the output of a request to
```
.../FeatureServer/0/query?f=json&returnCountOnly=true&returnGeometry=false&spatialRel=esriSpatialRelIntersects&where=1%3D1
```
e.g. 
```{"count":123123}```
> GSR: Give `returnCountOnly` precedence in query request

- src/community/gsr/src/main/java/org/geoserver/gsr/function/GSRFunctionFactory.java
- src/community/gsr/src/main/java/org/geoserver/gsr/function/GSRLog10.java
- src/community/gsr/src/main/java/org/geoserver/gsr/function/GSRStrIndexOf.java
- src/community/gsr/src/main/resources/META-INF/services/org.geotools.filter.FunctionFactory
- src/community/gsr/src/test/java/org/geoserver/gsr/function/GSRFunctionFactoryTest.java
We've found that GSR doesn't support the same query syntax as Esri during `where` filters in Feature query requests.
For example, a request like this, which is typical from Esri while filtering, results in an 'invalid CQL' error:
```
/query?f=json&where=(1=1)%20AND%20LOWER(FIELD)=%test%27
```
The CQL source (i.e. `(1=1)%20AND%20LOWER(FIELD)=%test%27`) is parsed straight from the URL into creating a new `Filter`.
The `AbstractFilterBuilder` class then identifies in the source if there is a function to build. 
If there is, it will take the name of the function and see if that function name is registered in any of the `FunctionFactory` classes. ([Source](https://github.com/koordinates/geotools/blob/6a1de8f8ca614acaa6a21f3565e1a0eccaaaf1a8/modules/library/main/src/main/java/org/geotools/filter …
> GSR: `GSRFunctionFactory` to register SQL functions to their equivalent ECQL functions

- src/community/gsr/src/main/java/org/geoserver/gsr/api/GSRFeatureResultPBF.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/MapServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureLayer.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureList.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureDAO.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/QueryControllerTest.java
**Note: New flags**
Ref: https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#typedefinitions-summary
- `supportsPagination`: Indicates if the query response supports pagination.
- `maxRecordCount`: The maximum number of records that will be returned for a given query. Set to 30000
- `maxRecordCountFactor` ([Ref](https://developers.arcgis.com/javascript/latest/api-reference/esri-rest-support-Query.html#maxRecordCountFactor)): When set, the maximum number of features returned by the query will equal the maxRecordCount of the service multiplied by this factor. The value of this property may not exceed 5.
**QueryController** must now take `resultOffset` and `resultRecordCount` query parameters. 
Ref: …
> GSR: Support Query Pagination

- src/community/gsr/src/main/java/org/geoserver/gsr/api/GSRFeatureResultPBF.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/MapServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureLayer.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureList.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureDAO.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/ObjectIdRemappingFilterVisitor.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/QueryControllerTest.java
**Note: New flags**
Ref: https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#typedefinitions-summary
- `supportsOrderBy`: Indicates if features returned in the query response can be ordered by one or more fields.
- `supportsDistinct`: Indicates if the layer supports queries for distinct values based on fields specified in the [`outFields`](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#outFields).
**QueryController** now takes `orderByFields (string[])` and `returnDistinctValue (boolean)` query parameters. 
Ref: https://developers.arcgis.com/rest/services-reference/enterprise/query-feature-service-layer/
- `returnDistinctValues`: If true then the query returns distinct values based on the field(s) …
> GSR: Support sorting by fields & distinct values

- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/MapServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureLayer.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureStatistics.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/StatisticTypeEnum.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureDAO.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/QueryControllerTest.java
**Note: New flags**
Ref: https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#typedefinitions-summary
- `supportsStatistics`: Indicates if the layer supports field-based statistical functions.
**QueryController** now takes `outStatistics (Object[])` and `groupByFieldsForStatistics (String[])` query parameters. 
- [`outStatistics`](https://developers.arcgis.com/javascript/latest/api-reference/esri-rest-support-Query.html#outStatistics): The definitions for one or more field-based statistics to be calculated. If outStatistics is specified the only other query parameters that should be used are [`groupByFieldsForStatistics`](https://developers.arcgis.com/javascript/latest/api-reference/esri-rest-support-Query.html#groupByFieldsForStatistics), …
> GSR: Support Basic Statistical Queries

- src/community/gsr/src/main/java/org/geoserver/gsr/api/GSRFeatureResultPBF.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/MapServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureLayer.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureStatistics.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/StatisticTypeEnum.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureDAO.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/QueryControllerTest.java
This PR contains two main fixes:
- For Coordinate Systems with metre unit: it's required to be a double but it's currently performing an Integer operation. Returning `1e-9` for radians so return the equivalent of (1/10000) = `1e-4`
- Handle basic string expressions in `orderByFields` parameter
- Sorting (string) fields in ArcPRO does a request with an `UPPER()` function in the  `orderByFields` parameter. eg. `orderByFields=UPPER(field)`
`orderByFields` is case-insensitive anyways, so there's not much point evaluating these expressions.
Furthermore, it doesn't support all string expressions (eg. `CONCAT`, `SUBSTRING`)...
So ignore the string expressions as of now.
> GSR: Fix scale values, and handle sort fields with SQL expression

- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
For some layers, GSR returns a negative object id. 
This behaves weirdly in AGOL, as it maps it to massive numbers.
The only possible case where GSR could return negative numbers is when the regex doesn't match and we return the hashcode of the layer identifier.
We can set this to always be positive - which is what I have done, but then there is also a small chance/risk of duplicate ID.
- This was because the layer had a PK field set to a string field. Causing the `featureId` string to not contain digits and thus not match the pattern.
> GSR: Ensure that objectids are always positive

- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureServiceRoot.java
- src/community/gsr/src/test/java/org/geoserver/gsr/function/GSRFunctionFactoryTest.java
Add the `capabilities` field to the feature service root object. 
`Query` should be the only valid capability here.
Added `geojson` and `PBF` to supported query formats aswell. 
Also fixed a bug where the `GSRFunctionFactoryTest` was initialised with the wrong package naming.
> Feature Service Root: Add capabilities field

- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/MapServiceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureList.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureDAO.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
Couple of performance improvements:
* If we are returning distinct values, count, or ids, set `returnGeometry` to False. This will skip fetching the geometries for each feature. 
* Return the feature count before creating the `FeatureList`. It was done this way so that we ensure that we return the count of distinct values if `returnCountOnly` and `returnDistinctValues` were used in conjunction. However, `UniqueCountVisitor` exists, so we can use this to count the distinct field values if it is used in conjunction - allowing us to skip the iterator while creating `FeatureList`.
> GSR: Improve count query performance

- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureExtent.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureLayer.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/QueryControllerTest.java
`/query?returnExtentOnly=true` needs to be supported.
If `true`, the response only includes the extent of the features that would be returned by the query. If `returnCountOnly=true` , the response will return both the count and the extent. The default is `false` . This parameter applies only if the `supportsReturningQueryExtent` property of the layer is `true`
Values: `true` | `false`
Ref: https://developers.arcgis.com/rest/services-reference/enterprise/query-feature-service-layer/
> GSR: Support return extent only queries

- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureList.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/map/QueryControllerTest.java
I.e. Enabling `outFields` to have more than one fields when doing a `returnDistinctValues=true` query.
This change requires the `UniqueVisitor` class to have the change that supports multiple attributes.
See: https://github.com/koordinates/geotools/tree/backport-3844-to-25.x
`query?f=json&where=1=1&returnDistinctValues=true&outFields=type,status`
> GSR: Support multiple feature attributes for distinct value query

- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/QueryController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureLayer.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/FeatureList.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureDAO.java
Added parameters:
| Parameters | Description | Values |
| --- | --- | --- |
| `returnExceededLimitFeatures` | This option is supported by most feature services, except for feature services published using a spatiotemporal data store. This parameter is `true` by default. When set to `true` , features are returned even when the results include `exceededTransferLimit`: `true`. **When set to `false` and querying with `resultType` set to `tile` , features are not returned when the results include `exceededTransferLimit`: `true`** . This allows a client to find the resolution in which the transfer limit is no longer exceeded without making multiple calls. | Values: `true` / `false` |
| `resultType` | The `resultType` parameter can be used to control the number of features returned by the query …
> GSR: `returnExceededLimitFeatures` and `resultType` parameter support

- src/community/gsr/src/main/java/org/geoserver/gsr/api/GSRFeatureResultPBF.java
Negative values in ESRI Rest Profobuffer responses are encoded thusly:
```
attributes {
int64_value: -263260800000
}
```
At the moment this specifically manifests in datetimes that are before Unix epoch (1970), ie common in things like property tiles layers.
But should be `sint64_value`. Currently this causes clients to underflow a 64bit integer which generally breaks them.
> GSR PBF: Long values should be of sint64 type
